Elektrobit/flake-pilot

- launcher/Cargo.toml
- launcher/src/app_path.rs
- launcher/src/main.rs
- launcher/src/podman.rs
- launcher/src/tests.rs
Options to control how podman starts the container can now be
provided as ```/etc/pilot/program_name.yaml``` like the following
example shows:
```yaml
runtime:
--storage-opt: size=10G
--rm:
```
If no runtime configuration exists the following defaults apply
* Container resources will be automatically deleted after the call.
* Interactive sessions will be allowed
> Support program runtime config file

- doc/oci-pilot.rst
- oci-pilot/src/defaults.rs
- oci-pilot/src/podman.rs
- package/debbuild/oci-pilot.spec
Using resume in the flake setup will re-attach to the running container instead of starting a new one. This setting is useful for interactive container sessions as well as for long running processes, e.g services. This Fixes #32
> Added support for resume/respawn

- oci-pilot/src/defaults.rs
In line with the changes proposed to kiwi from here https://github.com/OSInside/kiwi/pull/2252
the file name to store removed files has been changed from 'vanished' to 'removed'
> Change the filename of the removed file reference

- doc/oci-ctl-register.rst
- oci-ctl/src/app.rs
- oci-ctl/src/app_config.rs
- oci-ctl/src/cli.rs
- oci-ctl/src/main.rs
- oci-ctl/template/flake.yaml
Allow to specify --attach or --resume setting at app registration.
This Fixes #48 and Fixes #39
> Add commandline switches for attach/resume setting

- doc/oci-ctl-podman-register.rst
- oci-ctl/src/app.rs
- oci-ctl/src/app_config.rs
- oci-ctl/src/cli.rs
- oci-ctl/src/main.rs
Allow to specify --run-as username as part of the flake registration. This Fixes #54
> Add support for user setting on the commandline

- doc/oci-ctl-podman-register.rst
- oci-ctl/src/app.rs
- oci-ctl/src/app_config.rs
- oci-ctl/src/cli.rs
- oci-ctl/src/main.rs
Allow to specify podman runtime options as part of the flake registration. This Fixes #41
> Add support for podman settings on the commandline

- doc/flake-ctl-podman-register.rst
- flake-ctl/src/app.rs
- flake-ctl/src/app_config.rs
- flake-ctl/src/cli.rs
- flake-ctl/src/defaults.rs
- flake-ctl/src/main.rs
- flake-ctl/src/podman.rs
If provided in the container the --info command will print the embedded default registration information. Along with the change some refactoring on the option handling as well as moving code engine specific vs. generic registration implementation. This Fixes #67
> Add support for --info to podman register command

- podman-pilot/src/podman.rs
If using additional container layers, the launcher should make sure they get pulled if not yet done.
> Make sure container layer get pulled in

- Makefile
- firecracker-pilot/guestvm-tools/sci/src/main.rs
- package/flake-pilot.spec
This patch is two fold:
* Package firecracker service command interface
* Fixed use of static variables
> Package sci

- package/flake-pilot.spec
Add flake-pilot-firecracker-guestvm-tools sub-package providing tools needed inside of the firecracker VM image to help implementing the application launcher workflow. Provides
> Add firecracker guest VM tools package

- .github/workflows/ci-compile.yml
- Makefile
- doc/flake-ctl-firecracker-pull.rst
- doc/flake-ctl-podman-build-deb.rst
- doc/flake-ctl-podman-load.rst
- doc/flake-ctl-podman-pull.rst
- doc/flake-ctl-podman-register.rst
- doc/flake-ctl-podman-remove.rst
- flake-ctl/Cargo.toml
- flake-ctl/src/cli.rs
- flake-ctl/src/defaults.rs
- flake-ctl/src/fetch.rs
- flake-ctl/src/firecracker.rs
- flake-ctl/src/main.rs
- package/flake-pilot.spec
Added support for flake-ctl firecracker pull
Added the pull command for the firecracker engine to download and register remote firecracker images into a local storage location below /var/lib/firecracker/images.
This Fixes #83
> Added support for flake-ctl firecracker pull

- Makefile
- firecracker-pilot/guestvm-tools/sci/src/main.rs
When used without an initrd it's not possible for the kernel to run the binary if it was upx compressed. For further details also let sci print the user env in debug mode
> Do not compress sci binary

- firecracker-pilot/dracut/etc/dracut.conf.d/extramodules.conf
- firecracker-pilot/dracut/usr/lib/dracut/modules.d/80netstart/module-setup.sh
- firecracker-pilot/dracut/usr/lib/dracut/modules.d/80netstart/netstart.sh
- package/flake-pilot.spec
The new package flake-pilot-firecracker-dracut-netstart supports users with building firecracker images that supports networking using systemd-networkd and systemd-resolved activated and persistent inside of the initrd. 
This is related to Issue #76
> Added dracut-netstart package for firecracker

- firecracker-pilot/guestvm-tools/sci/src/defaults.rs
- firecracker-pilot/guestvm-tools/sci/src/main.rs
When using arbitrary rootfs images it might happen that there is no /overlayroot mountpoint which we use in the pilot to setup an overlay. In addition search for tools like switch_root in the former location /sbin to stay backward compatible with linux versions prior the /usr/sbin move. Newer linux versions still maintains symlinks from /sbin to /usr/sbin for compat reasons.
> Make sure to create /overlayroot

- README.md
- doc/firecracker-pilot.rst
- doc/flake-ctl-firecracker-pull.rst
- doc/flake-ctl-firecracker-register.rst
- firecracker-pilot/guestvm-tools/sci/src/main.rs
- flake-ctl/src/app.rs
- flake-ctl/src/app_config.rs
- flake-ctl/src/cli.rs
- flake-ctl/src/defaults.rs
- flake-ctl/src/firecracker.rs
- flake-ctl/src/main.rs
So far pulling a firecracker image was limited to the KIWI kis image type. With this commit it's also possible to pull an image from it's components; rootfs, kernel and optional initrd. This allows for example to make use of the firecracker hosted CI images or any other rootfs image in combination with some kernel/initrd. During the pull of such an image there is also a check for the sci binary inside of the rootfs. If it does not exist it gets added to the rootfs such that the firecracker-pilot can work with it. This Fixes #99
> Support pulling image from components

- flake-ctl/src/defaults.rs
- flake-ctl/src/firecracker.rs
For firecracker the layout looks like the following:
/var/lib/firecracker/
├── images
└── storage
The code in flake-ctl setting it up only cared for the images subdirectory and did not allow /var/lib/firecracker to be a symlink location
> Fixed setup of firecracker registry layout

- firecracker-pilot/src/firecracker.rs
- firecracker-pilot/template/firecracker.json
This commit adds the init code to create a vsock per instance. This is related to Issue #87
> Add firecracker vsock at instance startup

- firecracker-pilot/src/defaults.rs
- firecracker-pilot/src/firecracker.rs
The CID in VM shall always be equall 3 as the connection generated by firecracker is vsock less connection, means static cid bound on vm to the unix domain socket bound on host
> FIX for wrongly handled CID in json configuration

- firecracker-pilot/src/firecracker.rs
The name of the uds socket was set to /run/sci_cmd_PID.sock The used PID was the firecracker process ID. This name doesn't make much sense because for one command registration there will always be only one dedicated firecracker process instance assigned. For the use case of --resume there can be multiple connections through the same uds socket
> Change name of UDS socket for vsock communication

- doc/firecracker-pilot.rst
- doc/flake-ctl-firecracker-register.rst
- firecracker-pilot/src/firecracker.rs
- flake-ctl/src/app.rs
- flake-ctl/src/app_config.rs
- flake-ctl/src/cli.rs
- flake-ctl/src/main.rs
Write sci_resume=1 to the boot cmdline arguments if --resume is set at app registration for the firecracker pilot. This is related to Issue #87
> Add resume support to firecracker app registration

- firecracker-pilot/Cargo.toml
- firecracker-pilot/guestvm-tools/sci/src/defaults.rs
- firecracker-pilot/guestvm-tools/sci/src/main.rs
- firecracker-pilot/src/defaults.rs
- firecracker-pilot/src/firecracker.rs
The former implementation used the vsock channel to read the command, call it in a child and send the output back through the vsock channel. This works until the command is not interactive. With this refactor I propose a different way to handle the command execution.
start vsock listener on VM_PORT, wait for command(s) in a loop. A received command turns into a
socat process using a pseudo terminal (pts) and output that can be retrieved by simply connecting
to the EXEC_PORT
Example:
```
sudo socat UNIX-CONNECT:/run/sci_cmd_XXX.sock -
CONNECT 52
ls -l
```
```
sudo socat UNIX-CONNECT:/run/sci_cmd_XXX.sock -
CONNECT 42
```
The above procedure needs to be implemeted as
part of the firecracker-pilot resume code
Thoughts ?
> Refactor sci for resume mode

- firecracker-pilot/guestvm-tools/sci/Cargo.toml
- package/flake-pilot.spec
By default sys_mount supports loop devices. In sci. We don't use them and for kernel 6.x the code does
not compile anymore and fails with: ```enum_(unnamed_at_/usr/include/linux/loop_h_16_1)" is not a valid Ident```
Newer distros e.g TW, Lobster, rawhide .... uses kernel 6.x and there the rust loop feature in sys_mout no longer
compiles. As it's a code path we never use, the disabling of the feature only has positive effects, less dependencies,
smaller binary size, compiles on kernel 6.x based distros
> Disable loop feature in sys_mount

- doc/flake-ctl-firecracker-register.rst
- firecracker-pilot/src/defaults.rs
- firecracker-pilot/src/firecracker.rs
- flake-ctl/src/app.rs
- flake-ctl/src/app_config.rs
- flake-ctl/src/cli.rs
- flake-ctl/src/main.rs
- podman-pilot/src/podman.rs
This commit implements reading of the flake include section for the firecracker pilot. With the include tar support it's possible to provision any arbitrary data into the VM instance prior launch. For firecracker the include feature requires the use of an overlay. This Fixes #95
> Add firecracker include provisioning

- helper/update_changelog.py
Add missing license information to update_changelog.py license is MIT in alignment with the overall flake-pilot license. The license setting is in agreement with the only copyright holder of the software which is the person of this signed commit. This Fixes #125
> Clarify on license

- doc/Makefile
- doc/firecracker-pilot.rst
- doc/flake-ctl-firecracker-register.rst
- doc/flake-ctl-firecracker-remove.rst
- doc/flake-ctl-podman-register.rst
- doc/flake-ctl-podman-remove.rst
- doc/podman-pilot.rst
- package/flake-pilot.spec
pandoc is pretty big and adds a lot of haskel lib requirements rst2man just requires python3-docutils and is more lightweight
> Use rst2man instead of pandoc to render man pages

- podman-pilot/Cargo.toml
- podman-pilot/src/app_path.rs
- podman-pilot/src/config.rs
- podman-pilot/src/main.rs
- podman-pilot/src/podman.rs
- podman-pilot/src/tests.rs
first part of https://github.com/Elektrobit/flake-pilot/issues/128
Includes only podman config, will copy the approach for firecracker and/or create generic version for all back ends if approved
Adds lazy_static for config initialization, can be removed if rust version is bumped to one that includes [OnceCell](https://doc.rust-lang.org/stable/std/cell/struct.OnceCell.html)
> Replace adhoc yaml with serde

- podman-pilot/Cargo.toml
- podman-pilot/src/config.rs
- podman-pilot/src/error.rs
- podman-pilot/src/main.rs
- podman-pilot/src/podman.rs
Builds on top of #131 
Replaces all `unwrap()`, `panic!()` and `exit()` calls in podman.rs with Errors that are propagated to back up to the main function.
1. Makes function API cleaner and more consistent
3. Clearly marks which functions can error
4. `Result` is a 'must_use' type, so errors can no longer be missed on accident
5. Enables cleanup of an error state in the future by not terminating immediately
Since all errors simply propagate back up to `main()` the external behavior should be completely unchanged except for some hard coded error messages (could be added back in if needed).
Sorry for the big diff, but this time it's not possible to make it smaller since almost all return types were changed. Diff could be reduced in size by only adding `Result` to some methods, but this …
> Better error handling

- firecracker-pilot/src/firecracker.rs
- podman-pilot/src/podman.rs
Fixes #139 
Moves the spinners to stderr so the flakes produce a clean output on stdout
> Moved spinners to stderr

- Makefile
- package/flake-pilot.spec
Updated the Makefile and the .spec file to fit the new structure with a top level Cargo.toml
This also reduces the package size by combining the vendored dependencies
[This time it even builds!](https://build.opensuse.org/package/show/home:Ichmed:branches:home:marcus.schaefer:delta_containers/flake-pilot)
> Makefile v2

- Cargo.toml
- common/Cargo.toml
- common/src/lib.rs
- common/src/user.rs
- firecracker-pilot/Cargo.toml
- firecracker-pilot/src/config.rs
- firecracker-pilot/src/firecracker.rs
- podman-pilot/Cargo.toml
- podman-pilot/src/config.rs
- podman-pilot/src/podman.rs
Create a `User` struct and move the 
```rust
let mut command = Command::new("sudo");
if let Some(user) = user {
command.arg("--user").arg(user);
}
command.arg(<program>);
```
pattern there.
Now you can write
```rust
let mut command = user.run(<program>);
```
This is only a small first step, we should think about moving other structs and functions (like chmod) into the common lib. Especially the config structs so flake-ctl and the pilots can share them.
> Extract common code

- doc/firecracker-pilot.rst
- firecracker-pilot/Cargo.toml
- firecracker-pilot/src/defaults.rs
- firecracker-pilot/src/firecracker.rs
When using the firecracker-pilot in a resume type flake, the pilot creates a UDS socket for listening on data. Each of this socket connections requires a free port. The former implementation selects the socket by a random number within a given range. However, this is not a stable solution and the risk to select an already occupied port is high. This commit refactors the port allocation to a simply calculate a new port from FIRECRACKER_VSOCK_PORT_START + the PID of the pilot process.
* This selection for a free port is also not completely stable as there could be other services on the OS that occupies the selected port for which firecracker-pilot has no information.
Further conversations on this topic brought up some ideas how to select a system wide free port by e.g a kernel module but as …
> Refactor port allocation for UDS socket

- Cargo.toml
- Makefile
- firecracker-pilot/Cargo.toml
- firecracker-pilot/firecracker-service/service-communication/Cargo.toml
- firecracker-pilot/firecracker-service/service/Cargo.toml
- flake-ctl/Cargo.toml
- package/flake-pilot.spec
- podman-pilot/Cargo.toml
If there is no any particular reasons why we should not remove symbols information, then this should be activated back. However I do see the reason not to UPX-compress the release binaries by default, because it does not do any impact on memory-allocated size, however, it burns CPU to unpack the binary every launch, while disk is cheap. Some systems detect UPX compressed binaries as a virus, which only adds to the problem.
Whoever still needs UPX can use `make compress` as an extra step.
> Reactivate binary stripping

- common/Cargo.toml
- common/src/config/cfg_v1.rs
- common/src/config/cfg_v2.rs
- common/src/config/itf.rs
- common/src/config/mod.rs
Now configuration can be loaded from one place, paths are taken automatically and all the data from `.d` directories is merged:
```rust
let myconf = flakes::config::load()?;
```
> Add config loader and path resolver

- common/src/config/cfg_v1.rs
- common/src/config/cfg_v2.rs
- common/src/config/itf.rs
- common/src/config/pilots/fc.rs
- common/tests/cfg_ut.rs
- common/tests/cfg_ut_v2.rs
- common/tests/data/cfg-v2/all.yaml
This PR updates path map section interface for v2 config with aliases, where each alias allows different exported flake behaviour.
> v2: path aliases for different behaviours

- pilots/src/oci-pilot/fgc.rs
- pilots/src/oci-pilot/prunner.rs
Garbage collector works on background, but should not double-check the current CID.
> Skip current CID while GC

- pilots/src/oci-pilot/podman.rs
- pilots/src/oci-pilot/prunner.rs
Directly forward the output and input of attached containers to the caller instead of buffering them.
This fixes the issue of interactive apps getting stuck or terminating immediatly
> Oci-tty-fix
