- doc/oci-pilot.rst
- oci-pilot/src/podman.rs
Run engine (e.g podman) through sudo and allow custom user setting. This Fixes #33
> Run engine through sudo

- oci-pilot/Cargo.lock
- oci-pilot/Cargo.toml
- oci-pilot/src/podman.rs
During delta provisioning take all removed files information from all containers used in the provisioning process into account. This Fixes #46
> Take all removed files into consideration

- doc/oci-pilot.rst
- oci-pilot/src/main.rs
- oci-pilot/src/podman.rs
Allow calling the application with different caller options in the same container instance. This Fixes #45
> Refactor resume behavior

- Makefile
- oci-ctl/Cargo.lock
- oci-ctl/Cargo.toml
- oci-ctl/src/app_config.rs
- oci-ctl/src/defaults.rs
- oci-ctl/template/flake.yaml
- package/oci-pilot.spec
Use serde for reading/writing yaml content.
This Fixes #40
> Refactor yaml processing

- podman-pilot/Cargo.toml
- podman-pilot/src/podman.rs
Add a spinner to show progress during provisioning This Fixes #59
> Add spinner to feedback user on progress

- .bumpversion.cfg
- Makefile
- firecracker-pilot/firecracker-service/service-communication/Cargo.toml
- firecracker-pilot/firecracker-service/service/Cargo.toml
- package/flake-pilot-rpmlintrc
- package/flake-pilot.spec
Provide sub-packages flake-pilot-podman and flake-pilot-firecracker
This Fixes #72
> Refactor packaging

- doc/firecracker-service.rst
- package/flake-pilot.spec
Firecracker-service man page. This Fixes https://github.com/Elektrobit/flake-pilot/issues/77
> firecracker-service manual page

- Makefile
- doc/flake-ctl-firecracker-register.rst
- doc/flake-ctl-firecracker-remove.rst
- flake-ctl/src/app.rs
- flake-ctl/src/app_config.rs
- flake-ctl/src/cli.rs
- flake-ctl/src/defaults.rs
- flake-ctl/src/firecracker.rs
- flake-ctl/src/main.rs
- flake-ctl/src/podman.rs
- flake-ctl/template/firecracker-flake.yaml
- package/flake-pilot.spec
Add app registration/removal for the firecracker engine This Fixes #84
> Add flake-ctl firecracker register/remove

- Makefile
- doc/firecracker-pilot.rst
- doc/podman-pilot.rst
- firecracker-pilot/Cargo.toml
- firecracker-pilot/src/app_path.rs
- firecracker-pilot/src/defaults.rs
- firecracker-pilot/src/firecracker.rs
- firecracker-pilot/src/main.rs
- firecracker-pilot/template/firecracker.json
- package/flake-pilot.spec
The firecracker-pilot launcher binary will run the registered application through firecracker. This Fixes #86
> Add firecracker-pilot launcher

- doc/flake-ctl-firecracker-register.rst
- firecracker-pilot/Cargo.toml
- firecracker-pilot/src/firecracker.rs
- flake-ctl/src/cli.rs
- package/flake-pilot.spec
Use native methods to create a sparse overlay file
> Get rid of qemu tools to create sparse file

- README.md
Those parts of the network setup for firecracker instances that cannot be done in code (or out of scope for this project) are documented with this commit as one possible example This Fixes #76
> Add network configuration guide

- Makefile
- firecracker-pilot/guestvm-tools/sci/Cargo.toml
- package/flake-pilot.spec
- package/gcc_fix_static.sh
This would allow to incorporate it into any arbitrary rootfs
> Build sci as static binary

- firecracker-pilot/src/firecracker.rs
When using a firecracker instance in resume mode the first call has to run firecracker in the background, open a connection to the vsock and send the command. Any subsequent call only sends commands to the existing instance. If the instance gets deleted the pilot has to check if the VM is still there and behave properly. Meaning vmid (PID) and uds socket file must be cleaned up prior launching a new instance. The commit here implements the processing of this workflow. It does not implement the actual connection to the instance and sending of commands. This will follow. As of now only debug messages telling what should happen are printed. This is related to Issue #87
> Added instance resume process to firecracker pilot

- firecracker-pilot/guestvm-tools/sci/src/main.rs
- firecracker-pilot/src/firecracker.rs
In resume mode sci calls commands through a vsock using socat EXEC. This commit makes sure that the quoting of the command string doesn't get lost and becomes effective at socket connection time. This Fixes #113
> Fixed sci command quoting in resume mode

- .github/workflows/ci-sbom.yml
- firecracker-pilot/Cargo.toml
- firecracker-pilot/firecracker-service/service-communication/Cargo.toml
- firecracker-pilot/firecracker-service/service/Cargo.toml
- firecracker-pilot/guestvm-tools/sci/Cargo.toml
- flake-ctl/Cargo.toml
- podman-pilot/Cargo.toml
This PR adds:
- Missing license spec in all TOML configs of each subpackage
- License lister for all vendored subpackages (the entire tree)
> Fix licenses and add more actions

- .github/workflows/clippy.yml
- Cargo.toml
- firecracker-pilot/firecracker-service/service-communication/src/lib.rs
- firecracker-pilot/guestvm-tools/sci/src/defaults.rs
- firecracker-pilot/guestvm-tools/sci/src/main.rs
- firecracker-pilot/src/app_path.rs
- firecracker-pilot/src/defaults.rs
- firecracker-pilot/src/firecracker.rs
- flake-ctl/src/app.rs
- flake-ctl/src/app_config.rs
- flake-ctl/src/cli.rs
- flake-ctl/src/deb.rs
- flake-ctl/src/fetch.rs
- flake-ctl/src/firecracker.rs
- flake-ctl/src/podman.rs
- podman-pilot/src/app_path.rs
- podman-pilot/src/defaults.rs
- podman-pilot/src/main.rs
- podman-pilot/src/podman.rs
- podman-pilot/src/tests.rs
- Added a Clippy action to Github.
- Fixed all Clippy warnings and errors except for function argument numbers
- Fixed up some (but not all) unidiomatic code
The Action will run for every push for now and fail if any Clippy warnings are generated. There is a nicer vrsion that annotates the code with the warnings directly but I could not get it to run https://github.com/actions-rs/clippy-check
All code should be semantically identical except for flake-ctl/src/app_config.rs#134 which now removes ALL leading slashes, not just one, could be a problem but I don't know enough about the app yet.
> Automated Clippy Action

- flake-ctl/src/main.rs
Fixes #140 
Still needs a more elegant error handling in the future (right now there are multiple ways to exit the program) but this lets the tests run at least
> Flake ctl returncode

- firecracker-pilot/Cargo.toml
- firecracker-pilot/src/config.rs
- firecracker-pilot/src/firecracker.rs
- firecracker-pilot/src/main.rs
Changes to the config mirroring those already made for podman
Also see #128
> Firecracker config

- doc/firecracker-pilot.rst
- firecracker-pilot/Cargo.toml
- firecracker-pilot/src/defaults.rs
- firecracker-pilot/src/firecracker.rs
Reverts Elektrobit/flake-pilot#154
> Revert "Refactor port allocation for UDS socket"

- rustfmt.toml
Add formatting configuration to further prevent 1960'ies.
> Add formatter config

- podman-pilot/Cargo.toml
- podman-pilot/src/error.rs
- podman-pilot/src/main.rs
- podman-pilot/src/podman.rs
> Podman cleanup

- Makefile
- robot_tests/ctl/firecracker.robot
- robot_tests/ctl/podman.robot
This is what happens when you don't have firecracker tests
> Added flake-ctl-firecracker to install

- common/src/config/mod.rs
> Move cid storage to a subdirectory
